name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-24.04 ]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Build
        run: ./gradlew build --no-daemon

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ClearSkies-Artifacts
          path: build/libs/*
          if-no-files-found: error
